import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/toaster";
import { getServerAuthSession } from "@/server/auth";
import { ThemeProvider } from "@/components/theme-provider";
import { UserAccountNav } from "@/components/user-account-nav";
import { MainNav } from "@/components/main-nav";
import BuyerConfig from "@/config/buyer";
import SellerConfig from "@/config/seller";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

let navItems: { title: string; href: string; description?: string }[] = [];

export default async function RootLayout({
  children,
  buyer,
  seller,
}: {
  children: React.ReactNode;
  buyer: React.ReactNode;
  seller: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  if (session?.user) {
    const role = session?.user.role;
    if (role === "BUYER") {
      navItems = BuyerConfig.nav;
      return <Layout>{buyer}</Layout>;
    }
    if (role === "SELLER") {
      navItems = SellerConfig.nav;
      return <Layout>{seller}</Layout>;
    }
  }

  return <Layout>{children}</Layout>;
}

function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`relative h-dvh w-dvw font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="sticky top-0 z-40 border-b bg-background/40 backdrop-blur">
              <div className="container flex h-16 items-center justify-between py-4">
                <MainNav items={navItems} />
                <UserAccountNav />
              </div>
            </header>
            <main className="absolute top-0 min-h-full min-w-full  pt-16">
              {children}
            </main>
          </ThemeProvider>
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
