import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { getServerAuthSession } from "@/server/auth";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
  buyer,
  seller,
}: {
  children: React.ReactNode;
  buyer: React.ReactNode;
  seller: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  if (session?.user) {
    const role = session?.user.role;
    if (role === "BUYER") return <Layout>{buyer}</Layout>;
    if (role === "SELLER") return <Layout>{seller}</Layout>;
  }

  return <Layout>{children}</Layout>;
}

function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
